version: '3.8'

services:
  server:
    container_name: isaac-script-dispatcher
    build:
      context: .
      args:
        APP_PRIVATE_KEY: ${APP_PRIVATE_KEY}
        GITHUB_WEBHOOK_SECRET: ${GITHUB_WEBHOOK_SECRET}
        GITHUB_API_SECRET: ${GITHUB_API_SECRET}
        GITHUB_APP_IDENTIFIER: ${GITHUB_APP_IDENTIFIER}
        GITHUB_INSTALLATION_ID: ${GITHUB_INSTALLATION_ID}
    image: isaac-script-dispatcher
    ports:
      - "5000:5000"
    volumes:
      - ./scripts:/app/scripts
      - ${PHY_CONTENT_PATH}:/app/data/rutherford-content
      - ${CS_CONTENT_PATH}:/app/data/ada-content
