version: '3.8'

services:
  server:
    container_name: isaac-script-dispatcher
    build:
      context: .
      args:
        SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
    image: isaac-script-dispatcher
    ports:
      - "5000:5000"
    volumes:
      - ./scripts:/app/scripts
      - ${PHY_CONTENT_PATH}:/app/data/phy
      - ${CS_CONTENT_PATH}:/app/data/cs
