version: '2'

services:
  server:
    container_name: isaac-script-dispatcher
    build:
      context: .
      args:
        GITHUB_WEBHOOK_SECRET: ${GITHUB_WEBHOOK_SECRET}
        GITHUB_API_SECRET: ${GITHUB_API_SECRET}
        GITHUB_APP_IDENTIFIER: ${GITHUB_APP_IDENTIFIER}
        GITHUB_INSTALLATION_ID: ${GITHUB_INSTALLATION_ID}
    volumes:
      - ${APP_PRIVATE_KEY_PATH}:/app/key.pem:ro
    restart: always
networks:
  default:
    external:
      name: isaac
